const SET_USERS = 'SET_USERS';
const ADD_USER = 'ADD_USER';
const REMOVE_USER = 'REMOVE_USER';

const SET_ROOMS = 'SET_ROOMS';
const REMOVE_ROOM = 'REMOVE_ROOM';
const ADD_ROOM = 'ADD_ROOM';
const CHANGE_ROOM = 'CHANGE_ROOM';

const CREATE_CONNECTION = 'CREATE_CONNECTION';
const CHANGE_LOCATION = 'CHANGE_LOCATION';
const SET_GAME = 'SET_GAME';
const START_GAME = 'START_GAME';
const FINISH_GAME = 'FINISH_GAME';

const TOGGLE_CHAT = 'TOGGLE_CHAT';
const ACTIVATE_TAB = 'ACTIVATE_TAB';
const ADD_CHAT_TAB = 'ADD_CHAT_TAB';
const HIDE_CHAT_TAB = 'HIDE_CHAT_TAB';
const SHOW_CHAT_TAB = 'SHOW_CHAT_TAB';
const ADD_PENDING_TAB = 'ADD_PENDING_TAB';
const REMOVE_PENDING_TAB = 'REMOVE_PENDING_TAB';
const ADD_MESSAGE = 'ADD_MESSAGE';

export {
	SET_USERS,
	ADD_USER,
	REMOVE_USER,

	SET_ROOMS,
	ADD_ROOM,
	REMOVE_ROOM,
	CHANGE_ROOM,

	CHANGE_LOCATION,
	CREATE_CONNECTION,
	SET_GAME,
	START_GAME,
	FINISH_GAME,

	TOGGLE_CHAT,
	ACTIVATE_TAB,
	ADD_CHAT_TAB,
	HIDE_CHAT_TAB,
	SHOW_CHAT_TAB,
	ADD_PENDING_TAB,
	REMOVE_PENDING_TAB, 
	ADD_MESSAGE
}